name: Android pull request test

on:
  pull_request:
    branches:
      - '*'

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build, test, and lint
      run: ./scripts/recursive.sh clean checkstyle assembleAlphaRelease lintAlphaRelease testAlphaRelease
