# This is a basic workflow to help you get started with Actions
name: Android test and alpha update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_alpha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build, test, and lint
        run: ./gradlew clean checkstyle assembleAlphaRelease lintAlphaRelease testAlphaRelease
      - name: List
        run: ls -alR ./app/build/outputs/apk/
      - uses: r0adkll/sign-android-release@v1
        name: Sign Apk
        id: build_signed
        with:
          releaseDirectory: app/build/outputs/apk/alpha/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Create hash
        run: git rev-parse HEAD > app/build/outputs/apk/alpha/release/rev-hash.txt
      - name: Rename APK to universal
        run: mv app/build/outputs/apk/alpha/release/app-alpha-release-signed.apk app/build/outputs/apk/alpha/release/app-alpha-universal-release.apk
      - uses: dev-drprasad/delete-tag-and-release@v0.1.2
        name: Delete latest alpha tag
        with:
          delete_release: false
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1
        name: Create release and upload artifacts
        with: 
          name: latest
          commit: master
          tag: latest
          artifacts: "app/build/outputs/apk/alpha/release/app-alpha-universal-release.apk,app/build/outputs/apk/alpha/release/rev-hash.txt"
          body: This is the latest Alpha version of the app (Autogenerated).
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replaceArtifacts: true
